version: "3.8"
services:
  triton_lenet:
    command: ["--model-repository=/models", "--log-info=1"]
    build: .
    shm_size: "32gb"
    restart: unless-stopped
    ports:
      - 8500:8000
      - 8501:8001
      - 8502:8002
    volumes:
      - ./:/workspace
      - ./model_repository:/models
      - ./assets:/assets
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    deploy:
      resources:
        limits:
          cpus: "2"
        # reservations:
        # devices:
        # - driver: nvidia
        #   device_ids: ['2']
        #   capabilities: [gpu]
