dataset:
  path: "data/flowers/split.csv"
  image_height: 224
  image_width: 224
  crop_scale: 0.2

model:
  type: "lenet"
  num_classes: 4
  channels:
    - 16
    - 32
    - 64
    - 128
    - 256

experiment:
  path_to_weights: "weights/"
