dataset:
  path: "data/flowers/split.csv"
  image_height: 224
  image_width: 224
  crop_scale: 0.2

model:
  type: "lenet"
  num_classes: 4
  channels:
    - 16
    - 32
    - 64
    - 128
    - 256

  optimizer:
    type: "adam"
    params:
      lr: 0.0003
      weight_decay: 0.0001

experiment:
  path_to_weights: "weights/"
